server:
  address: ":8000"
  readTimeout: "60s"
  writeTimeout: "0"
  idleTimeout: "60s"
  maxHeaderBytes: "10240"
  keepAlive: true
  serverAgent: "GoFrame HTTP Server"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  serverRoot: "./resource/public"
  fileServerEnabled: true
  cookieMaxAge: "365d"
  cookiePath: "/"
  sessionMaxAge: "24h"
  sessionIdName: "gfsessionid"

logger:
  path: "/app/logs/"
  file: "{Y-m-d}.log"
  level: "all"
  stdout: true

database:
  logger:
    path: "/app/logs/sql"
    level: "all"
    stdout: true
    ctxKeys: [ "RequestId" ]

  default: &db_default
    link: "mysql:${MYSQL_USER:modulith_open}:${MYSQL_PASSWORD:pwd}@tcp(${MYSQL_HOST:mysql}:${MYSQL_PORT:3306})/${MYSQL_DATABASE:modulith_open}?loc=Local&parseTime=true"
    debug: ${DEBUG:false}

  # 使用默认配置
  sys:
    <<: *db_default
  account:
    <<: *db_default
  pay:
    <<: *db_default
  store:
    <<: *db_default
  pt:
    <<: *db_default
  order:
    <<: *db_default
  shop:
    <<: *db_default
  admin:
    <<: *db_default
  cms:
    <<: *db_default

redis:
  default:
    address: ${REDIS_HOST:redis}:${REDIS_PORT:6379}
    db: ${REDIS_DB:0}
    pass: ${REDIS_PASSWORD:}
    idleTimeout: "60s"
    maxConnLifetime: "90s"

# 其他配置保持不变
secure:
  publicKey: ${PUBLIC_KEY:MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDBT2vr+dhZElF73FJ6xiP181txKWUSNLPQQlid6DUJhGAOZblluafIdLmnUyKE8mMHhT3R+Ib3ssZcJku6Hn72yHYj/qPkCGFv0eFo7G+GJfDIUeDyalBN0QsuiE/XzPHJBuJDfRArOiWvH0BXOv5kpeXSXM8yTt5Na1jAYSiQ/wIDAQAB}
  privateKey: ${PRIVATE_KEY:MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAMFPa+v52FkSUXvcUnrGI/XzW3EpZRI0s9BCWJ3oNQmEYA5luWW5p8h0uadTIoTyYweFPdH4hveyxlwmS7oefvbIdiP+o+QIYW/R4Wjsb4Yl8MhR4PJqUE3RCy6IT9fM8ckG4kN9ECs6Ja8fQFc6/mSl5dJczzJO3k1rWMBhKJD/AgMBAAECgYEAucMakH9dWeryhrYoRHcXo4giPVJsH9ypVt4KzmOQY/7jV7KFQK3x//27UoHfUCak51sxFw9ek7UmTPM4HjikA9LkYeE7S381b4QRvFuf3L6IbMP3ywJnJ8pPr2l5SqQ00W+oKv+w/VmEsyUHr+k4Z+4ik+FheTkVWp566WbqFsECQQDjYaMcaKw3j2Zecl8T6eUe7fdaRMIzp/gcpPMfT/9rDzIQk+7ORvm1NI9AUmFv/FAlfpuAMrdL2n7p9uznWb7RAkEA2aP934kbXg5bdV0R313MrL+7WTK/qdcYxATUbMsMuWWQBoS5irrt80WCZbG48hpocJavLNjbtrjmUX3CuJBmzwJAOJg8uP10n/+ZQzjEYXh+BszEHDuw+pp8LuT/fnOy5zrJA0dO0RjpXijO3vuiNPVgHXT9z1LQPJkNrb5ACPVVgQJBALPeb4uV0bNrJDUb5RB4ghZnIxv18CcaqNIft7vuGCcFBAIPIRTBprR+RuVq+xHDt3sNXdsvom4h49+Hky1b0ksCQBBwUtVaqH6ztCtwUF1j2c/Zcrt5P/uN7IHAd44K0gIJc1+Csr3qPG+G2yoqRM8KVqLI8Z2ZYn9c+AvEE+L9OQY=}
